---
- hosts: all

  tasks:

     - name: Installs apache web server
       apt: pkg=apache2 state=installed update_cache=true
       sudo: yes
       notify:
         - start apache

  handlers:

     - name: start apache
       service: name=apache2 state=started